/* Generated By:JavaCC: Do not edit this line. MiniJavaParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 1;
  /** RegularExpression Id. */
  int LEFT_BRACE = 2;
  /** RegularExpression Id. */
  int PUBLIC = 3;
  /** RegularExpression Id. */
  int STATIC = 4;
  /** RegularExpression Id. */
  int VOID = 5;
  /** RegularExpression Id. */
  int MAIN = 6;
  /** RegularExpression Id. */
  int LEFT_PARENTHESES = 7;
  /** RegularExpression Id. */
  int STRING = 8;
  /** RegularExpression Id. */
  int LEFT_BRACKET = 9;
  /** RegularExpression Id. */
  int RIGHT_BRACKET = 10;
  /** RegularExpression Id. */
  int RIGHT_PARENTHESES = 11;
  /** RegularExpression Id. */
  int RIGHT_BRACE = 12;
  /** RegularExpression Id. */
  int EXTENDS = 13;
  /** RegularExpression Id. */
  int SEMICOLON = 14;
  /** RegularExpression Id. */
  int RETURN = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int INT = 17;
  /** RegularExpression Id. */
  int BOOLEAN = 18;
  /** RegularExpression Id. */
  int ASSIGN = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int ELSE = 21;
  /** RegularExpression Id. */
  int WHILE = 22;
  /** RegularExpression Id. */
  int SYSTEM_OUT_PRINTLN = 23;
  /** RegularExpression Id. */
  int AND = 24;
  /** RegularExpression Id. */
  int LESS_THAN = 25;
  /** RegularExpression Id. */
  int PLUS = 26;
  /** RegularExpression Id. */
  int MINUS = 27;
  /** RegularExpression Id. */
  int TIMES = 28;
  /** RegularExpression Id. */
  int DOT = 29;
  /** RegularExpression Id. */
  int LENGTH = 30;
  /** RegularExpression Id. */
  int TRUE = 31;
  /** RegularExpression Id. */
  int FALSE = 32;
  /** RegularExpression Id. */
  int THIS = 33;
  /** RegularExpression Id. */
  int NEW = 34;
  /** RegularExpression Id. */
  int NOT = 35;
  /** RegularExpression Id. */
  int DIGIT = 36;
  /** RegularExpression Id. */
  int LETTER = 37;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 38;
  /** RegularExpression Id. */
  int IDENTIFIER = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"class\"",
    "\"{\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"(\"",
    "\"String\"",
    "\"[\"",
    "\"]\"",
    "\")\"",
    "\"}\"",
    "\"extends\"",
    "\";\"",
    "\"return\"",
    "\",\"",
    "\"int\"",
    "\"boolean\"",
    "\"=\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"System.out.println\"",
    "\"&&\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\".\"",
    "\"length\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"new\"",
    "\"!\"",
    "<DIGIT>",
    "<LETTER>",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 43>",
    "<token of kind 44>",
  };

}
